name: test suite

# Pushes to long living branches and all PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        rust-version: ["1.70.0", "1.74.0", "1.78.0", "1.83.0", "1.87.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.rust-version }}"
          targets: "wasm32-unknown-unknown"
      - run: cargo build
      - run: cargo build --target wasm32-unknown-unknown

  build-no_std:
    strategy:
      matrix:
        rust-version: ["1.70.0", "1.74.0", "1.78.0", "1.83.0", "1.87.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.rust-version }}"
          targets: "thumbv6m-none-eabi"
      - run: cargo check --no-default-features --target thumbv6m-none-eabi

  test:
    strategy:
      matrix:
        rust-version: ["1.70.0", "1.74.0", "1.78.0", "1.83.0", "1.87.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.rust-version }}"
      - run: cargo test

  test-no_std:
    strategy:
      matrix:
        rust-version: ["1.70.0", "1.74.0", "1.78.0", "1.83.0", "1.87.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.rust-version }}"
      - run: cargo test --no-default-features

  clippy:
    strategy:
      matrix:
        rust-version: ["1.70.0", "1.74.0", "1.78.0", "1.83.0", "1.87.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.rust-version }}"
          components: "clippy"
      - run: cargo clippy --all-targets -- -D warnings
